INSERT INTO Dictionary VALUES (NULL, and, и; а, но, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, friend, друг, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, a, неопределенный артикль, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, felt, чувствовал, войлок, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, to, к, в, на, до, для, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, three, три, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, was, был, была, было;, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, knew, знал, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, I, я, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, another, другой, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, is, 3- е л. ед. ч. наст. врем. гл. to be, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, once, один раз, однажды, когда-то, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, of, из, от, о, об, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, give, давать, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, that, тот, та, то, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, almost, почти, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, you, ты, вы, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, mind, разум; мнение, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, he, он, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, took, брал, хватал, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, it, он, она, оно; это, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, light, свет; освещать(ся), NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, in, в, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, yes, да, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, his, его, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, love, любовь, любить, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, had, имел, получал, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, end, конец; кончать(ся), NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, do, делать, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, boy, мальчик, парень, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, with, с, вместе с, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, looking, смотреть, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, not, не, нет; ни, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, while, в то время как, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, her, её, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, sound, звук; звучать, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, for, в течение, на, для, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, moment, миг, момент, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, on, на, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, men, люди, мужчины, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, at, около, у; в, на, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, ever, когда-либо, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, but, только, лишь, кроме, но, а, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, under, под; ниже, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, she, она, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, told, говорил, рассказывал, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, him, его, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, really, действительно, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, as, как, когда, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, life, жизнь, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, are, мн. ч. наст. врем. гл. to be, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, world, мир, свет; вселенная, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, said, говорил, сказал, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, same, тот же самый, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, they, они, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, sure, уверенный; конечно, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, we, мы, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, new, новый, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, all, все, вся, всё, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, found, находил, встречал, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, this, этот, эта, это, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, being, жизнь, существование, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, have, иметь; получать; быть должным, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, enough, достаточно, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, there, там, туда, здесь, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, gone, ушли, ушёл, ушедший, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, what, что, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, many, много, многие, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, out, вне, снаружи; за, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, big, большой, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, up, наверх(у), выше; вверх по, вдоль по, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, does, 3-е л. ед. наст. времени от do, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, one, один, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, every, каждый, всякий, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, from, от, из, с, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, began, начинал, начиналось, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, me, мне, меня, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, always, всегда, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, go, идти, ехать ; уходить, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, girl, девочка, девушка, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, were, были, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, home, дом, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, would, 1) вспом. глагол.; 2) модальный глагол, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, without, без, в отсутствие, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, like, похожий; как, подобно; любить, нравиться, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, heard, слышал, услышал, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, when, когда, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, toward, к, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, could, мог, умел, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, need, нуждаться, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, then, тогда; затем, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, stop, остановка; останавливать(ся), NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, be, быть, существовать; находиться, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, maybe, может быть, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, them, их , им, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, part, доля, часть, отчасти, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, did, делал, выполнял, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, use, использовать, применять, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, been, был, была, было, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, okay, хорошо!, ладно!, есть!, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, now, теперь, сейчас, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, look, взгляд, смотреть, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, though, хотя, даже, тем не менее, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, back, спина, задний, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, far, дальний; далеко, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, my, мой, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, name, имя; название, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, no, нет, не, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, word, слово, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, your, твой, ваш, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, behind, за; сзади , позади, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, which, который; что, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, try, пытаться, пробовать, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, about, кругом, вокруг; около; о, об, относительно, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, help, помощь; помогать, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, time, время; раз, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, also, тоже, также, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, down, вниз, внизу; вниз по, вдоль по, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, better, лучший, наилучший, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, into, в, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, mean, середина; значить; подразумевать, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, who, кто; который, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, father, отец, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, can, мочь; уметь, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, against, против, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, know, знать, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, anything, что-нибудь; что угодно, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, if, если, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, start, начало; начинать(ся), NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, just, только что, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, yet, ещё, всё ещё, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, their, их, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, walk, ходьба; ходить, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, get, получать; брать; приобретать, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, woman, женщина, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, over, над; свыше, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, seen, видел, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, more, больше, более, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, close, близкий, тесный; близко; закрывать(ся), NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, some, несколько, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, remember, помнить, вспоминать, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, man, человек, мужчина, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, car, автомобиль, машина, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, come, приходить, приезжать; случаться, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, between, между, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, an, неопределённый артикль, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, until, до, (до тех пор) пока (не), NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, so, так; тоже, также, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, both, оба, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, other, другой, иной, еще, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, done, сделанный; выполненный, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, little, маленький, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, god, бог, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, see, видеть, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, find, находить, обнаруживать, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, here, здесь, тут, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, water, вода, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, thing, вещь, предмет, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, arm, рука;, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, hand, рука, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, few, немного; a ~ несколько, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, by, у , около, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, hear, слышать; слушать, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, will, 1) вспом. гл. будущ. врем.; 2) модальный глагол, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, dog, собака, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, way, путь, дорога, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, happen, случаться, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, again, опять, снова, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, its, его, её (о предмете), NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, right, правый; верно, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, book, книга, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, only, только, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, morning, утро, утренний, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, am, 1-е л. ед.ч. наст. врем. гл. to be, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, kid, ребёнок, малыш, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, how, как, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, street, улица, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, think, думать; считать, полагать, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, believe, верить, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, or, или, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, talk, разговор; говорить, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, got, получил, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, mother, мать, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, good, хороший; добро, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, kind, сорт, разряд; вид, класс, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, eye, глаз; взгляд, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, coming, прибытие, приезд,, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, well, хорошо, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, each, каждый, всякий, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, thought, думал, мысль, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, black, черный, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, day, день; сутки, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, half, половина, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, two, два, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, red, красный, алый, рыжий, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, than, чем, нежели, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, stood, стоял, водружал, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, before, перед; раньше, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, young, молодой, юный, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, where, где; куда, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, shall, вспомогательный и модальный глагол, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, very, очень, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, show, показ;  показывать, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, say, говорить, сказать, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, feet, ноги, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, came, приходил, приезжал, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, feel, чувствовать, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, any, какой-нибудь, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, keep, держать, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, old, старый, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, next, следующий; будущий; потом, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, still, тихий; все еще, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, dark, тёмный, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, after, после, через; потом, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, along, вдоль, по, рядом, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, off, с , от, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, pass, проход, путь, передавать, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, has, имел, имела, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, course, курс, ход, течение, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, never, никогда, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, window, окно, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, going, живущий, существующий, ходьба, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, dead, мертвый, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, even, даже; ровно, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, hour, час, время, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, much, много, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, wanted, разыскиваемый полицией, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, went, шёл, ехал, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, matter, вещество, материал, иметь значение, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, too, также; слишком, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, since, с тех пор, с, после, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, away, далеко; прочь, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, cry, плакать, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, something, что-то, что-нибудь; примерно, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, heart, сердце, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, first, первый; сначала, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, answer, ответ, отвечать; откликаться, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, make, делать, производить; совершать, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, small, маленький, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, head, голова, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, yeah, да, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, want, хотеть, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, doing, дела, акт, действие, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, turn, поворачивать(ся), NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, four, четыре, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, face, лицо, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, move, двигать(ся), NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, made, сделан, сделанный, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, live, жить, существовать,, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, seem, казаться, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, suddenly, вдруг, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, call, призыв; звать, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, five, пять, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, ask, спрашивать, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, body, тело, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, should, 1) вспом. глагол; 2)  должен, следует, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, fire, огонь; пожар; стрелять; поджигать, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, through, через , сквозь, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, mouth, рот, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, long, длинный; долго, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, leave, покидать, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, let, позволять, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, smile, улыбка; улыбаться, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, take, брать; доставлять; принимать, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, state, государство, страна, штат, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, saw, видел, пила, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, family, семья, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, around, кругом, вокруг; поблизости, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, road, дорога, путь, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, our, наш, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, front, передний, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, door, дверь, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, laugh, смех, смеяться, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, last, последний, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, gave, давал, передавал, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, tell, говорить, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, across, через, сквозь; поперек, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, might, мог, мог бы, энергия, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, step, шаг; шагать, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, own, свой; владеть, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, quite, вполне, совершенно; полностью, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, night, ночь; вечер, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, change, менять, изменять, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, year, год, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, later, позже, более поздний, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, must, должен, обязан, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, together, вместе; совместно, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, because, потому что, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, soon, скоро, вскоре, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, voice, голос, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, least, минимальный, наименьший, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, such, такой, тот, подобный, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, second, секунда; второй, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, room, комната, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, kill, убивать, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, place, место; помещать, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, watch, 1) смотреть, следить; наблюдение; 2) часы, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, those, те, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, wife, жена, супруга, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, work, работа; работать, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, hard, жёсткий, твёрдый, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, put, положить, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, wait, ждать, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, bill, счёт, законопроект, клюв, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, sat, сидел, находился, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, nothing, ничего, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, feeling, ощущение, чувство, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, most, самый большой, наибольший, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, high, высокий, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, house, дом, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, guy, парень, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, why, почему, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, idea, идея; мысль, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, may, мочь; май, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, line, линия; черта, строка, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, side, сторона, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, fear, боязнь, страх, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, great, большой, великий, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, miss, потеря, утрата, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, these, эти, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, bad, плохой, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, white, белый, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, hair, волосы, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, people, люди, нация, народ, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, minute, минута, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, upon, на, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, everything, всё, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, left, левый, налево, покинул, уехал, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, please, пожалуйста, желать, хотеть, NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, open, открывать(ся), NULL, NULL)
INSERT INTO Dictionary VALUES (NULL, tshirt, футболка, NULL, NULL)
